// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RobotMaintenanceApi.Data;

#nullable disable

namespace RobotMaintenanceAPI.Migrations
{
    [DbContext(typeof(RobotDbContext))]
    [Migration("20260819082655_SeedRobots")]
    partial class SeedRobots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RobotMaintenanceApi.Model.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMaintenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextMaintenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Robots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastMaintenance = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "XR-7",
                            Name = "Atlas",
                            NextMaintenance = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Operational"
                        },
                        new
                        {
                            Id = 2,
                            LastMaintenance = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "MK-II",
                            Name = "Hammer",
                            NextMaintenance = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NeedsMaintenance"
                        },
                        new
                        {
                            Id = 3,
                            LastMaintenance = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "RX-12",
                            Name = "Bishop",
                            NextMaintenance = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Operational"
                        },
                        new
                        {
                            Id = 4,
                            LastMaintenance = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "MK-I",
                            Name = "Rustbucket",
                            Status = "OutOfService"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
